
'use client';

import type { Event, Booking } from '@/types';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/hooks/useAuth';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { Ticket, CreditCard, Loader2, CheckCircle, AlertTriangle } from 'lucide-react';
import { QRCodeDisplay } from './QRCodeDisplay';
import { useToast } from '@/hooks/use-toast';
import { collection, addDoc, serverTimestamp, updateDoc, doc } from 'firebase/firestore';
import { db } from '@/lib/firebase/config';
import { generateDisplayTicketId } from '@/lib/ticketUtils';

interface EventBookingClientProps {
  event: Event;
}

export function EventBookingClient({ event }: EventBookingClientProps) {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const { toast } = useToast();
  const [bookingState, setBookingState] = useState<'idle' | 'processing' | 'booked' | 'error'>('idle');
  const [bookedDetails, setBookedDetails] = useState<Booking | null>(null);
  // generatedBookingId will store the actual Firestore doc.id for QR code data
  const [generatedBookingId, setGeneratedBookingId] = useState<string | null>(null); 

  const handleBookNow = async () => {
    if (authLoading) return;
    if (!user) {
      router.push(`/login?redirect=/events/${event.id}`);
      return;
    }

    setBookingState('processing');

    try {
      // Simulate payment processing (Razorpay would be integrated here)
      await new Promise(resolve => setTimeout(resolve, 1500)); 

      const paymentId = `mock_payment_${Date.now()}`;
      
      // Firestore document ID will be generated by addDoc
      // const displayId = generateDisplayTicketId(docRef.id); // Will be generated after docRef.id is available

      const bookingDataForFirestore: Omit<Booking, 'id' | 'bookingDate' | 'qrCodeData' | 'displayTicketId'> & { qrCodeData?: string, displayTicketId?: string, userEmail?: string } = {
        userId: user.uid,
        userEmail: user.email || undefined, // Store user email
        eventId: event.id,
        eventTitle: event.title,
        eventDate: event.date,
        eventTime: event.time,
        paymentStatus: 'completed',
        paymentId: paymentId,
        verified: false,
        paymentCurrency: 'INR',
      };
      
      const docRef = await addDoc(collection(db, 'bookings'), {
        ...bookingDataForFirestore,
        bookingDate: serverTimestamp(), 
      });

      const actualBookingId = docRef.id;
      const displayId = generateDisplayTicketId(actualBookingId);
      
      // The qrCodeData should use the actual, unique Firestore booking ID for reliable verification
      const compositeQrCodeDataString = actualBookingId; // Simplified: QR now directly contains the booking ID
      
      await updateDoc(doc(db, 'bookings', actualBookingId), { 
        qrCodeData: compositeQrCodeDataString,
        displayTicketId: displayId,
      });
      
      const newBookingForDisplay: Booking = {
        ...bookingDataForFirestore,
        id: actualBookingId,
        displayTicketId: displayId,
        qrCodeData: compositeQrCodeDataString, 
        bookingDate: new Date() as any, 
        userEmail: user.email || undefined,
      };

      setBookedDetails(newBookingForDisplay);
      setGeneratedBookingId(actualBookingId); 
      setBookingState('booked');
      toast({
        title: "Booking Confirmed!",
        description: `${event.title} booked. Ticket ID: ${displayId}. (Payment: ₹${event.offerAmount || event.amount})`,
        duration: 7000,
      });

    } catch (error) {
      console.error("Booking failed:", error);
      setBookingState('error');
      toast({
        variant: "destructive",
        title: "Booking Failed",
        description: "Something went wrong. Please try again.",
      });
    }
  };

  if (bookingState === 'booked' && bookedDetails && generatedBookingId) {
    return (
      <div className="mt-8 p-6 bg-green-50 border border-green-200 rounded-lg shadow-md text-center">
        <CheckCircle className="h-16 w-16 text-green-500 mx-auto mb-4" />
        <h3 className="text-2xl font-semibold text-green-700 mb-2">Booking Confirmed!</h3>
        <p className="text-green-600 mb-1">Your ticket for <strong>{event.title}</strong> is ready.</p>
        <p className="text-green-600 mb-1">Amount paid: ₹{event.offerAmount || event.amount}</p>
        <p className="text-md font-semibold text-green-700 mb-4">Ticket Reference: {bookedDetails.displayTicketId}</p>
        
        {/* QR Code data is the actual Firestore booking ID (generatedBookingId) */}
        <QRCodeDisplay 
          qrDataToEncode={generatedBookingId} 
          displayTicketId={bookedDetails.displayTicketId}
          eventTitle={event.title}
          verifiableId={generatedBookingId}
        />
        <Button onClick={() => router.push('/profile')} className="mt-6 bg-green-600 hover:bg-green-700">
          View My Bookings
        </Button>
      </div>
    );
  }
  
  if (bookingState === 'error') {
     return (
      <div className="mt-8 p-6 bg-red-50 border border-red-200 rounded-lg shadow-md text-center">
        <AlertTriangle className="h-16 w-16 text-red-500 mx-auto mb-4" />
        <h3 className="text-2xl font-semibold text-red-700 mb-2">Booking Failed</h3>
        <p className="text-red-600 mb-4">We couldn't process your booking. Please try again.</p>
        <Button onClick={() => setBookingState('idle')} variant="destructive" className="mt-6">
          Try Again
        </Button>
      </div>
    );   
  }

  return (
    <div className="mt-8 pt-6 border-t">
      <Button
        onClick={handleBookNow}
        disabled={authLoading || bookingState === 'processing'}
        size="lg"
        className="w-full bg-accent hover:bg-accent/90 text-accent-foreground text-lg py-3"
      >
        {bookingState === 'processing' ? (
          <Loader2 className="mr-2 h-5 w-5 animate-spin" />
        ) : (
          <Ticket className="mr-2 h-5 w-5" />
        )}
        {authLoading ? 'Loading...' : (bookingState === 'processing' ? 'Processing...' : `Book Now & Pay ₹${event.offerAmount || event.amount}`)}
      </Button>
      <p className="text-xs text-muted-foreground mt-2 text-center flex items-center justify-center">
        <CreditCard className="h-3 w-3 mr-1"/> Secure payment (Demo Mode)
      </p>
    </div>
  );
}
